### ISSUE TITLE
Provide license file

### ISSUE THREAD

**Issue by proinsias** [dedupeio/doublemetaphone#1]
I'm working on submitting this package to [conda-forge](https://conda-forge.github.io/) – see my [PR](https://github.com/conda-forge/staged-recipes/pull/1365). As part of this, I would like to include a license file for this project. 

Could you please add one to the project and to the MANIFEST.in file?

**Comment by fgregg** [comment]
I was pretty sloppy here, because I the upstream work by @slacy doesn't have a clear license. I'm happy to add a license for my work (the cython code), but we also need him to provide a license for his work, the c++ code.  https://github.com/slacy/double-metaphone/

**Comment by proinsias** [comment]
Thanks for filing the [issue](https://github.com/slacy/double-metaphone/issues/1).

**Comment by sarimak** [comment]
The underlying C++ library's license seems to be Perl license which means either GPL 1+ or Artistic license (liberal, allows commercial re-distribution).

Since the referenced request to the author of the C++ library is unsolved for many years, could this wrapper select the Artistic license in good faith based on the available knowledge and notify the author of the C++ library so he can disagree?

If this sounds like a safe move, could you please add https://choosealicense.com/licenses/artistic-2.0/ as LICENSE.txt to this repo's root?

Could you also please add the license metadata to the PIP package?

**Comment by fgregg** [comment]
Sounds good. Can you make a PR?
